### ISSUE TITLE
Dados de Agencia e Conta de Bancos

### ISSUE THREAD

**Issue by CSIRTBRADESCO** [MrAbade/arquive-formatter#1]
Prezado Vinicius, poderia por gentileza remover os dados de Agencia e Conta constantes no arquivo accounts.txt?

Entendemos que a exposição destas informações pessoais não são fundamentais para este projeto e não deveriam estar públicas.

Poderia nos ajudar?

**Comment by MrAbade** [comment]
Olá. Posso certamente ajudar.

Os dados bancários das pessoas constantes no arquivo accounts.txt são fictícios.

Este repositório foi criado no intuito de apresentar algumas estruturas da linguagem Python para um grupo de devs em desenvolvimento, para o qual sou facilitador.

Vou remover o arquivo accounts.txt, mas apenas gostaria de reiterar que nenhum indivíduo teve suas informações pessoais expostas ou foi lesado de alguma forma, todos os dados contidos no arquivo foram criados para fins didáticos.

**Comment by CSIRTBRADESCO** [comment]
Obrigado pela pronta ajuda! Entendemos o cunho educativo e não tem intenção de expor dados de correntistas de nenhuma informação e foi criado somente para exemplificar o funcionamento da aplicação criada. Se estes dados bancários mesmo que gerados de forma aleatória existirem em qualquer instituição, podem de alguma forma não terem sido autorizadas pelos correntistas.
Em tempo, ainda que tenha removido o arquivo o Github deixa o histórico dessa alteração publicada. É possível recuperar tais informações através de seu repositório, poderia remover esta informação para que não seja mais acessada?

**Comment by CSIRTBRADESCO** [comment]
Vinicius, boa tarde.
Verificamos que o arquivo ainda encontra-se disponível para visualização.
Reinteramos o pedido para que a exposição destas informações seja excluída.
